GET http://localhost:3001

###

GET http://localhost:3000/villes


###

GET http://localhost:3000/villes/66150266a9433210119f43f6


###

DELETE http://localhost:3000/villes/661507b913ecda6dabc3ce77

###

PUT http://localhost:3000/villes/66150266a9433210119f43f6
Content-Type: application/json

{
    "ville": "Hiroshima",
    "first": "Modifier",
    "second": "test",
    "third": "test",
   "fourth": "test",
    "fifth": "test"
}

###

POST http://localhost:3000/villes
Content-Type: application/json

{
    "ville": "Tokyo",
    "first": "test",
    "second": "test",
    "third": "test",
   "fourth": "test",
    "fifth": "test"
}