GET http://localhost:3000

###

GET http://localhost:3000/error

###

GET http://localhost:3000/villes


###

GET http://localhost:3000/villes/66150266a9433210119f43f6


###

DELETE http://localhost:3000/villes/66151803c99ac591a3ba30f8

###

PUT http://localhost:3000/villes/66150266a9433210119f43f6
Content-Type: application/json

{
    "ville": "Hiroshima",
    "first": "Modifier",
    "second": "test",
    "third": "test",
   "fourth": "test",
    "fifth": "test"
}

###

POST http://localhost:3000/villes
Content-Type: application/json

{
    "ville": "Kenjaku",
    "first": "qaqa",
    "second": "a",
    "third": "qaqa",
   "fourth": "qaaqa",
    "fifth": "qaaqa"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "JIJIII@test.com",
    "password": "Testttt"
}

###

POST http://localhost:3000/auth/signin/phone
Content-Type: application/json

{
    "phoneNumber": "0606060606",
    "password": "Testttt"
}

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "Test@test.com",
    "password": "Azerty01",
    "name": "Jo",
    "phoneNumber": "0707070707"
}
